
tasks:
    - name: Install dependencies
      command: |
        export PIP_USER=false
        make install

vscode:
  extensions:
    - github.copilot
    - toba.vsfire
    - wix.vscode-import-cost
    - aaron-bond.better-comments
    - perkovec.emoji
    - ms-python.vscode-pylance
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - randomfractalsinc.vscode-data-preview
    - k--kato.intellij-idea-keybindings