
tasks:
    - name: Install dependencies
      command: |
        export PIP_USER=false
        make install
    - name: Generate config
      command: |
        eval $(gp env -e)
        pip3 install yq
        echo "$SEARCH_CONFIG" | yq -y > config.yaml

vscode:
  extensions:
    - github.copilot
    - toba.vsfire
    - wix.vscode-import-cost
    - aaron-bond.better-comments
    - perkovec.emoji
    - ms-python.vscode-pylance
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - randomfractalsinc.vscode-data-preview
    - k--kato.intellij-idea-keybindings
    - trungngo.autoflake