vector_database: supabase

# https://supabase.com
supabase_url: "https://xxxxx.supabase.co"
supabase_key: "xxxxx"

# https://app.pinecone.io/
## index name
pinecone_index: "my index name"
# replace this with your environment
pinecone_environment: "us-east1-gcp"
pinecone_api_key: ""

embedding_provider: openai

# https://platform.openai.com/account/api-keys
openai_api_key: "sk-xxxxxxx"
# https://platform.openai.com/account/org-settings
openai_organization: "org-xxxxx"

# https://dashboard.cohere.ai
cohere_api_key: "xxxxx"

# authentication
# auth: firebase # only firebase is supported for now
# firebase_service_account_path: "path/to/service-account.json"

# middlewares:
#   - middlewares.enrich.enrich.Enrich
#   - middlewares.processing_time.processing_time.ProcessingTime
