version: '3'

services:
  embedbase_dev:
    container_name: embedbase
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          uvicorn embedbase.__main__:app --reload --log-level debug --host 0.0.0.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - OPENAI_API_KEY={OPENAI_API_KEY}
    expose:
      - "8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5