services:
  - type: web
    name: embedbase-render
    env: python
    rootDir: .
    plan: free
    buildCommand: poetry install
    startCommand: "embedbase run"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.5
