apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-search-dev
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        startupProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 60
          successThreshold: 1
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 30

        image: gcr.io/obsidian-ai/obsidian-search:latest-dev
        env:
          - name: SENTRY_RELEASE
            value: "latest-dev"
          - name: ENVIRONMENT
            value: "development"
          - name: UPLOAD_BATCH_SIZE
            value: "100"
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
      volumes:
        - name: settings
          secret:
            secretName: OBSIDIAN_SEARCH
            items:
              - key: "3"
                path: .env
      timeoutSeconds: 120
