apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-search
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 5
      containers:
        startupProbe:
          # httpGet:
          #   path: /health
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 60
          exec:
            command:
              - /bin/sh
              - -c
              - |
                curl -X POST -H "Content-Type: application/json" -d '{"namespace": "integration-test", "notes": [{"note_path": "Bob.md", "note_tags": ["Humans", "Bob"], "note_content": "Bob is a human"}]}' http://localhost:8080/refresh

        image: gcr.io/obsidian-ai/obsidian-search:0.0.8
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
        env:
          - name: SENTRY_RELEASE
            value: "0.0.8"
          - name: ENVIRONMENT
            value: "production"
      volumes:
        - name: settings
          secret:
            secretName: OBSIDIAN_SEARCH
            items:
              - key: "2"
                path: .env
      timeoutSeconds: 240
