apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-search
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 5
      containers:
        startupProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 60

        image: gcr.io/obsidian-ai/obsidian-search:0.2.6
        env:
          - name: SENTRY_RELEASE
            value: "0.2.6"
          - name: ENVIRONMENT
            value: "production"
          - name: UPLOAD_BATCH_SIZE
            value: "100"
          - name: MAX_NOTE_LENGTH
            value: "1700"
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
      volumes:
        - name: settings
          secret:
            secretName: OBSIDIAN_SEARCH
            items:
              - key: "2"
                path: .env
      timeoutSeconds: 240
