version: '3.7'

services:
  embedbase:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./middlewares/processing_time/processing_time.py:/app/middlewares/processing_time/processing_time.py
      - ./middlewares/enrich/enrich.py:/app/middlewares/enrich/enrich.py

