version: '3.7'

services:
  embedbase:
    image: ghcr.io/another-ai/embedbase:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./svc.prod.json:/secrets_firebase/svc.prod.json
