# This workflow will do a clean install of dependencies, cache/restore them, build the source code and run tests across different versions of python

name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: make install

      - name: Read EMBEDBASE_TEST_CONFIG JSON secret and write it to config.yaml
        env:
          EMBEDBASE_TEST_CONFIG: ${{ secrets.EMBEDBASE_TEST_CONFIG }}
        run: |
          sudo apt-get update
          sudo apt-get install yq -y
          echo $EMBEDBASE_TEST_CONFIG | yq -P > config.yaml

      - name: Run tests
        run: make test
  