name: Embedbase JS SDK release

on:
  push:
    branches:
      - main
      - next
      - rc
    paths:
      - 'sdk/embedbase-js/**'
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ['16']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci
          npm run build
        working-directory: sdk/embedbase-js

      - name: Run tests
        run: |
          npm clean-install
          npm run test:coverage
        working-directory: sdk/embedbase-js
        env:
          EMBEDBASE_API_KEY: ${{ secrets.EMBEDBASE_API_KEY }}
          BANKRUPT_EMBEDBASE_KEY: ${{ secrets.BANKRUPT_EMBEDBASE_KEY }}
          # necessary hack otherwise ci running in parallel create concurrency issues
          EMBEDBASE_DATASET: release_sdk_js_unit_test

      - name: Create a release
        run: npx semantic-release@^18.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: sdk/embedbase-js
